name: "Chinese DOS Games"
description: "在浏览器中玩经典中文DOS游戏"
version: "1.0.1"  # 增加版本号
slug: "dos_games"
url: "https://github.com/simkcy/ha-addon-dos-games"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
ports:
  "5000/tcp": 5000
map:
  - share:rw
boot: "auto"
options: {}
schema: {}
